name: 📚 Documentation
description: Report documentation issues
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be documented?
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Which page needs updating?