name: '👋 Welcome'

on:
  fork:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
  discussion:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Greet New Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.COFFEE_SHOP_GITHUB_TOKEN }}
          issue-message: |
            ### Welcome @${{ github.actor }}! 🌟

            Thank you for opening your first issue! We're excited to have you here.

            A few quick things:
            - 📝 Please check if this issue has been reported before
            - ✅ Follow our issue template if provided
            - ⏳ We'll review your issue as soon as possible

            Need help? Check our [Contributing Guidelines](CONTRIBUTING.md)
            
          pr-message: |
            ### Amazing Work @${{ github.actor }}! 🎉

            Thank you for your first pull request! We're thrilled to have you here.

            Helpful resources:
            - 📚 [Contributing Guidelines](CONTRIBUTING.md)
            - 🔧 [Development Setup](DEVELOPMENT.md)
            - ⭐ [Code of Conduct](CODE_OF_CONDUCT.md)

            We'll review your PR soon. Keep coding! 💻